# itk-version: 3.2.4
services:
  phpfpm:
    environment:
      - PHP_SENDMAIL_PATH=/usr/sbin/sendmail -S mail:1025

  nginx:
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:?}.middlewares=ITKBasicAuth@file"

  mail:
    image: axllent/mailpit
    restart: unless-stopped
    networks:
      - app
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.mail_${COMPOSE_PROJECT_NAME:?}-http.rule=Host(`mail.${COMPOSE_SERVER_DOMAIN:?}`)"
      - "traefik.http.routers.mail_${COMPOSE_PROJECT_NAME:?}-http.entrypoints=web"
      - "traefik.http.routers.mail_${COMPOSE_PROJECT_NAME:?}-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.mail_${COMPOSE_PROJECT_NAME:?}.rule=Host(`mail.${COMPOSE_SERVER_DOMAIN:?}`)"
      - "traefik.http.routers.mail_${COMPOSE_PROJECT_NAME:?}.entrypoints=websecure"
      - "traefik.http.services.mail_${COMPOSE_PROJECT_NAME:?}.loadbalancer.server.port=8025"
      - "traefik.http.routers.mail_${COMPOSE_PROJECT_NAME:?}.middlewares=ITKMailhogAuth@file"
